print("Enter any 2 numbers 'x' and 'y'")
num1= input('x: ')
num2= input('y: ')
num1= int(num1)
num2= int(num2)
print(" ")

print("[SUM]")
sum= (num1+num2)
sum= int(sum)
print("Sum of two numbers 'x' and 'y' are",sum)
print(" ")

print("[SUBRACTION]")
sub= (num2)-(num1)
sub= int(sub)
print("Subraction of number 'y' from 'x'",sub)
print(" ")

print("[PRODUCT]")
prod= (num1)*(num2)
prod= int(prod)
print("Product of two numbers 'x' and 'y' are",prod)
print(" ")

print("[POWER]")
prod1= (num1)*(num1)
print("Product of 'x' and 'x' are",prod1)
print("-----------------------------")
prod2= (num2)*(num2)
print("Product of 'x' and 'x' are",prod2)
print(" ")

print("[DIVISION]")
div= (num2)/(num1)
div= float(div)
print("Divsion of 'y' by 'x'",div)
